{% set name = "libsvm-official" %}
{% set version = "3.37.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/libsvm_official-{{ version }}.tar.gz
  sha256: 50dc3e118a92b43554160c2095d7f06325751a7b5dad097e401e11b64820d2cf
  patches:
    - win32.patch

build:
  noarch: python
  number: 0

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
  host:
    - libsvm =337
    - pip
    - python
    - setuptools
  run:
    - libsvm =337
    - python
    - scipy

test:
  imports:
    - libsvm
    - libsvm.svm
    - libsvm.svmutil
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://www.csie.ntu.edu.tw/~cjlin/libsvm
  summary: Python binding of LIBSVM
  license: BSD-3-Clause

extra:
  recipe-maintainers:
    - bkpoon
