{% set name = "libsvm-official" %}
{% set version = "3.32.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/libsvm-official-{{ version }}.tar.gz
  sha256: f5f013b65f30623a8b4fe2ec7d2ef7e728e987568884fefb6d37daa6eab5d31a
  patches:
    - win32.patch

build:
  noarch: python
  number: 0

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
  host:
    - libsvm =332
    - pip
    - python
  run:
    - libsvm =332
    - python
    - scipy

test:
  imports:
    - libsvm
    - libsvm.svm
    - libsvm.svmutil
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://www.csie.ntu.edu.tw/~cjlin/libsvm
  summary: Python binding of LIBSVM
  license: BSD-3-Clause

extra:
  recipe-maintainers:
    - bkpoon
